### ISSUE TITLE
Manually rotate

### ISSUE THREAD

**Issue by meivin123** [PixelsCommander/Propeller#11]
Hello,
is there a possibility to manually rotate the propeller?
So for example I have two buttons, one negative and one positive which twist counterclockwise or clockwise.

**Comment by PixelsCommander** [comment]
Just set propellers .angle property

**Comment by Zaniyar** [comment]
sorry for "opening" this old thread.


> Just set propellers `.angle` property


but the angle can only be set on initiation, the angle option is the initial angle. I tried to reinitiate the propeller with a new angle anytime I need to change the angle => This does not work, once the propeller object is set, it stays like that.

I tried to set .angle on the new object:
```
let myPropeller = $(".rotor").propeller(...);
myPropeller.angle = 90; //not working
myPropeller[0].angle = 90; //not working
```
how can I set the angle from outside of myPropeller and also trigger its onRotate callback?
