### ISSUE TITLE
Control from another div

### ISSUE THREAD

**Issue by bryane92** [PixelsCommander/Propeller#12]
Is it possible to control the propellor from another div? I have a div called pano and when the mouse dras on that div I want my other div named ng to rotate instead of the pano div. Is this possible?

**Comment by PixelsCommander** [comment]
Sure, use onRotate callback on the controller you are going to use as manipulator, and there change ```.angle``` of the second Propeller. You

**Comment by bryane92** [comment]
Denis,

Thanks that helped but I cant seem to get the first div to not rotate. So
now they just both rotate when i call onRotate for the first div heres what
I have

var prop =  new Propeller(document.getElementById('pano'),{
                        angle:0,

                        onRotate: function(){

                            $("#naviGuy").css("webkitTransform",
"rotate("+this.angle+"deg)");
                             console.log(this.angle);

                        }

                     });

**Comment by PixelsCommander** [comment]
Lets try to figure it out. Let me have a look at your project to get big
picture of what you are trying to achieve.

2015-04-21 17:19 GMT+02:00 bryane92 <notifications@github.com>:

**Comment by bryane92** [comment]
Okay it works in either chrome or safari. But when you drag the panorama I
want the red dot with the green light coming off it to rotate so you can
see where you are looking. http://turing.plymouth.edu/~besopko/SnrProj/
 I've attached two files the propeller code is in index.html

**Comment by PixelsCommander** [comment]
Think you are using wrong tooling and should just operate on CSS property instead of using Propeller.

**Comment by PixelsCommander** [comment]
It is hard to get similarity between radial rotation used in Propeller and panorama paning you are trying to do.

**Comment by bryane92** [comment]
Well I orginally used this $("#naviGuy").css("webkitTransform",
"rotate("+degree+"deg)"); to try and rotate it the amount of degrees i
moved, but I couldnt figure out how to compute the x and y to make it turn
correct. Thanks anyway

**Comment by bryane92** [comment]
I tried css but i couldnt really figure out how to take in the x and y axis
to make the element rotate since im using mouse positin it just the element
just resets after i reclick using the webkit transform from css

**Comment by PixelsCommander** [comment]
Just do some geometry. 

This will basically depend on angle of sight photo provide and it`s size in pixels. 

Pixels / angles = pixels in one degree

**Comment by bryane92** [comment]
Thats what I tried by using e.clientX and Y but everytime i click the mouse
it just resets the angles and the element goes back to the same starting
position.

**Comment by PixelsCommander** [comment]
That is why you should remind x/y on mousedown and compare it to actual

**Comment by PixelsCommander** [comment]
Why can not you remind angle and x/y if needed? =)

**Comment by bryane92** [comment]
I'm not 100% sure how to do it right now I have this
 var move = false;
  var drag = document.getElementById('pano');

  function mousedown(e){


        drag.addEventListener('mousemove', function(e){
           //need to divide by y or something



        if(move == true){
       var ng = $('#naviGuy');
        var offsetL = ng.offset().left;
        var offsetT = ng.offset().top;
        var center_x = (offsetL) + ($(ng).width()/2);
        var center_y = (offsetT) + ($(ng).height()/2);
        var mouse_x = e.pageX;
        var mouse_y = e.pageY;
        var radians = Math.atan2(mouse_x - center_x, mouse_y - center_y);
        var degree = (radians * (180 / Math.PI) * -1) + 100;
          console.log(mouse_x);
          $("#naviGuy").css("webkitTransform", "rotate("+degree+"deg)");

        }

        });

    }

Sorry for the coding but I thought this would have worked.

**Comment by PixelsCommander** [comment]
Do you want to calc horizontal angle?
