### ISSUE TITLE
how to rotate by javascript?

### ISSUE THREAD

**Issue by mike8625** [PixelsCommander/Propeller#17]
1. rotate by js
2.when init, i use 
new Propeller(document.getElementById('r'), {
            angle: 45,
 ...
i want to rotate by animation, and onRoate event  can fired.

**Comment by PixelsCommander** [comment]
It is pretty hard to understand what you are aiming for
Try var prop = new Propeller(node); prop.angle = 45

**Comment by mike8625** [comment]
sorry, my English is bad. 
var prop = new Propeller(node); 
prop.angle = 45;
it can work but it has no animation; prop.angle = 45; ----> 0 -> 45;  i want: 0->1-2-> 3-->4->....->45...... just like css  keyframes xxx 0%{transform: ratate(0)} 100%{tranform: rotate(45)};

**Comment by PixelsCommander** [comment]
use tween.js for smooth changing https://github.com/tweenjs/tween.js/
