### ISSUE TITLE
Is it possible to restrict the rotation between degrees?

### ISSUE THREAD

**Issue by blastframe** [PixelsCommander/Propeller#18]
Hello,
Excellent work here!

Is there a way to restrict the rotation of a propeller between, say, 300° and  45°? If there is inertia, will it bounce off of the boundary?

**Comment by PixelsCommander** [comment]
There is no way to set boundaries. Simpliest way of implementing this is to listen to onrotate and operate with this.angle from there. Also you may modify sources and introduce new API like deadZone.start / deadZone.end. Feel free to make a PR or ask me if need any help.
