### ISSUE TITLE
Drop support for IE8

### ISSUE THREAD

**Issue by rkunev** [PixelsCommander/Propeller#23]
First of all - great plugin!

Title says it all - drop support for ancient unsupported browsers. Just by removing the polyfills at the end of the source we get:
- Trimming the source code to 490 LOC which is -20% from the original
- Approx. 2KB smaller file size in production minified non-gzipped version. From 11.2KB to 9.32KB which is almost 2KB less (17% file size reduction)

[Can I use... Function#bind and set/get](http://caniuse.com/#feat=es5)
[Can I use... window.addEventListener](http://caniuse.com/#feat=addeventlistener)
[Can I use... window.getComputedStyle](http://caniuse.com/#feat=getcomputedstyle)

I can help with a PR.

**Comment by PixelsCommander** [comment]
@rkunev Hi, sorry for being silent. It was exactly my vacation when you created an issue. So found it now accidently. Sure, PR is more then welcome!
