### ISSUE TITLE
rotate element with lower z-index

### ISSUE THREAD

**Issue by nickcom** [PixelsCommander/Propeller#25]
I have a few elements stacked on top of each other. I would like to be able to apply propeller.js to one of the divs in the middle of the stack, and rotate that. 

In other words, is if possible for the mouse/touch inputs to be applied to a div other than the one on the top layer?

**Comment by PixelsCommander** [comment]
Yes, you may use pointer-events: none; in upper element CSS

**Comment by nickcom** [comment]
Great! I didn't know this

**Comment by PixelsCommander** [comment]
Check cross-browser compatibility for it http://caniuse.com/#feat=pointer-events . May not meet your compatibility policy
