### ISSUE TITLE
what is the syntax for accessing the methods?

### ISSUE THREAD

**Issue by nickcom** [PixelsCommander/Propeller#26]
sorry if this is obvious, but once I have initiated Propeller on a div, what is the way to access the stop method?

**Comment by PixelsCommander** [comment]
var propeller  = new Propeller(div);
propeller.stop();

2016-10-24 15:19 GMT+02:00 nickcom <notifications@github.com>:

**Comment by nickcom** [comment]
Thanks. But I'm using Propeller as a jquery plugin.

var $propeller = $('#div').propeller(options);
$propeller.stop(); 

this doesn't stop the rotation.

**Comment by nickcom** [comment]
am I doing something wrong with the jQuery syntax?

**Comment by PixelsCommander** [comment]
Could you create a CodePen or JSBin with this?

**Comment by nickcom** [comment]
sure. Here is one:

https://jsfiddle.net/zxeodu6j/4/

Note the button doesn't stop the spin. I also noticed that the spinning will stop of its own accord (without button press) which I don't believe is expected behaviour?

**Comment by PixelsCommander** [comment]
When using jQuery you may access propellers with **$.propeller.propellers** which is an array of ones you created. To be honest I would not recommend to use jQuery syntax unless you need it for some solid reason.
