### ISSUE TITLE
only rotate when click on a button

### ISSUE THREAD

**Issue by techashish12** [PixelsCommander/Propeller#30]

**Comment by PixelsCommander** [comment]
Please elaborate, create a fiddle if possible

**Comment by techashish12** [comment]
i want to check how many time object will be swipe (not rotate).

**Comment by PixelsCommander** [comment]
Sorry, I can not understand this. Do you want to detect if this was rotated on touch device? This is not a task for a library which manages rotation. Detect swipes with hammer.js etc
