### ISSUE TITLE
Support for Vue?

### ISSUE THREAD

**Issue by paulm17** [PixelsCommander/Propeller#39]
Any chance for support for Vue?

Something like:

    if (Window.Vue) {
        export {Propeller};
    }

I'm doing this right now, so I can use propeller in a component for Vue.

Thanks

**Comment by PixelsCommander** [comment]
Would you be able to make a PR for this?

**Comment by paulm17** [comment]
Sure, I'm finished up for today.  But it'll submit it for tomorrow.  Thanks for the quick reply!

**Comment by paulm17** [comment]
I couldn't work out a way of using using export along with jQuery being present.

Also the if statement I mention above definitely does not work.

For Vue/React to be supported, a separate branch probably needs to be created and then submitted to NPM.

Unfortunately, I'm seriously busy on a project.  So, I'll leave that as an exercise for you/someone else.  

For now, I'm happy to do the change my end every time Propeller updates.

I'll close this for now!

**Comment by Zaniyar** [comment]
its not possible to use import Propeller from 'Propeller' in react?
TypeError: Propeller__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor
