### ISSUE TITLE
OnDragStop fires several times when I launch the propeller

### ISSUE THREAD

**Issue by PixelsCommander** [PixelsCommander/Propeller#4]

**Comment by yexx** [comment]
Hi, I saw that this issue was closed, but there is a similar problem.
I saw that the plugins calls the functions on the method when the page loads, and doesn't call nothing after, even if i start and stop a drag movement

Codepen: http://codepen.io/yexx/pen/eWEJwa?editors=0111

**Comment by PixelsCommander** [comment]
Please try the latest version from GitHub or NPM
